import { Service } from '@/types';

export const dataServices: Service[] = [
    {
        title: 'Orangutan and Dayak Village Cruises',
        cruise: 'Rahai’i Pangun',
        slug: 'Rahai-i-Pangun',
        image: '/boats-01.jpeg',
        tag: 'MID WEEK',
        date: {
            checkIn: 'March 04, 2025',
        },
        cabin: 'Superior',
        price: '800',
        days: '2D1N',
    },
    {
        title: 'Orangutan and Dayak Village Cruises',
        cruise: 'Rahai’i Pangun',
        slug: 'Rahai-i-Pangun',
        image: '/boats-01.jpeg',
        tag: 'WEEKEND',
        date: {
            checkIn: 'March 08, 2025',
        },
        cabin: 'Double',
        price: '1.200',
        days: '3D2N',
    },
    {
        title: 'Tanjung Puting and Rainforest Expeditions',
        cruise: 'Spirit of Kalimantan',
        slug: 'spirit-of-kalimantan ',
        image: '/boats-01.jpeg',
        tag: 'WEEKEND',
        date: {
            checkIn: 'March 08, 2025',
        },
        cabin: 'Twin',
        price: '1.500',
        days: '3D2N',
    },
    {
        title: 'Tanjung Puting and Rainforest Expeditions',
        cruise: 'Spirit of Kalimantan',
        slug: 'spirit-of-kalimantan ',
        image: '/boats-01.jpeg',
        tag: 'WEEKEND',
        date: {
            checkIn: 'March 08, 2025',
        },
        cabin: 'Twin',
        price: '1.500',
        days: '3D2N',
    },
    {
        title: 'Tanjung Puting and Rainforest Expeditions',
        cruise: 'Spirit of Kalimantan',
        slug: 'spirit-of-kalimantan ',
        image: '/boats-01.jpeg',
        tag: 'WEEKEND',
        date: {
            checkIn: 'March 08, 2025',
        },
        cabin: 'Twin',
        price: '1.500',
        days: '3D2N',
    },
    {
        title: 'Tanjung Puting and Rainforest Expeditions',
        cruise: 'Spirit of Kalimantan',
        slug: 'spirit-of-kalimantan ',
        image: '/boats-01.jpeg',
        tag: 'WEEKEND',
        date: {
            checkIn: 'March 08, 2025',
        },
        cabin: 'Twin',
        price: '1.500',
        days: '3D2N',
    },
    {
        title: 'Tanjung Puting and Rainforest Expeditions',
        cruise: 'Spirit of Kalimantan',
        slug: 'spirit-of-kalimantan ',
        image: '/boats-01.jpeg',
        tag: 'WEEKEND',
        date: {
            checkIn: 'March 08, 2025',
        },
        cabin: 'Twin',
        price: '1.500',
        days: '3D2N',
    },
    {
        title: 'Tanjung Puting and Rainforest Expeditions',
        cruise: 'Spirit of Kalimantan',
        slug: 'spirit-of-kalimantan ',
        image: '/boats-01.jpeg',
        tag: 'WEEKEND',
        date: {
            checkIn: 'March 08, 2025',
        },
        cabin: 'Twin',
        price: '1.500',
        days: '3D2N',
    },
    {
        title: 'Tanjung Puting and Rainforest Expeditions',
        cruise: 'Spirit of Kalimantan',
        slug: 'spirit-of-kalimantan ',
        image: '/boats-01.jpeg',
        tag: 'WEEKEND',
        date: {
            checkIn: 'March 08, 2025',
        },
        cabin: 'Twin',
        price: '1.500',
        days: '3D2N',
    },
];
