import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@/Providers';
import { MainNavbar } from '@/components/ui/Main.navbar';
import { Open_Sans } from 'next/font/google';
import { ErrorAlert } from '@/components/Alert/Error.alert';
import { NotificationAlert } from '@/components/Alert/Notification.alert';

const openSans = Open_Sans({
    subsets: ['latin'],
    display: 'swap',
});
export const metadata: Metadata = {
    title: 'Transaction by Wow Borneo',
    description: 'Generated by create next app',
    icons: {
        icon: '/images/logo.svg',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased w-full mx-auto scroll-smooth overflow-x-hidden ${openSans.className}`}>
                <Providers>
                    <ErrorAlert />
                    <NotificationAlert />
                    <MainNavbar key={'navbar'} />
                    <main className="px-12" key={'main'}>
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    );
}
